import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={inter.className} lang={"en"}>
      <body
        className={
          "h-full bg-gradient-to-b from-saturated-blue from-0% to-dark-black to-100% bg-no-repeat"
        }
      >
        {children}
      </body>
    </html>
  );
}
